services:
  db:
    image: postgres:15
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nest_auth
      JWT_SECRET: super-secret-key
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:
